# GitHub workflow action when publishing a new release:
#   Deploy plugin to wordpress.org repository.
#   Adds {plugin-name}.{version}.zip to release assets.
#
# Define SVN_USERNAME, SVN_PASSWORD for wordpress.org credentials
# Organization or Repository : Settings -> Secrets and Variables -> Actions
#
# wordpress.org plugin slug is the repository name (lower case).
# Expects tag name to be version (M.m.p) with or without preceding "v" (v1.2.3 or 1.2.3)
# Expects wordpress.org assets (screenshots, icons, banners) to be in /.wp-assets.
# Uses .distignore or .gitattributes for exclusions from deployment.
#
# See: https://github.com/10up/action-wordpress-plugin-deploy/
# See: https://github.com/softprops/action-gh-release
#
# Version: 26.0814.1

name: On Release, deploy to WordPress SVN
on:
  # When a release is published
  release:
    types: [published]

permissions:
  contents: write

env:
  REPO_NAME: ${{ github.event.repository.name }}
  TAG_NAME:  ${{ github.ref_name }}

jobs:
  deploy:
    name: Deploy to WordPress SVN
    runs-on: ubuntu-latest
    steps:

    # Get plugin SLUG (lower-case) from REPO_NAME and VERSION (sans 'v') from TAG_NAME
    - name: Plugin-Slug
      run: |
        echo "SLUG=${REPO_NAME,,}" >>${GITHUB_ENV}
        echo "VERSION=${TAG_NAME#v}" >>${GITHUB_ENV}

    # Checkout the repository code
    - name: Checkout-Code
      uses: actions/checkout@v7

    # Deploy to WordPress trunk and tag, creating a WP installable .zip
    - name: WordPress-Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        ASSETS_DIR: .wp-assets
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}

    # Rename zip file with REPO_NAME name and version (tag)
    - name: Rename-Zip
      run: |
        mv ${SLUG}.zip ${REPO_NAME}.${VERSION}.zip

    # Upload {plugin-name}.{version}.zip to github release
    - name: Upload-Release-Asset
      uses: softprops/action-gh-release@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ github.workspace }}/${{ env.REPO_NAME }}.${{ env.VERSION }}.zip
